### PR TITLE
Opensbi

### PR DESCRIPTION
**Pull request by NathanTP**
**Type of change**: new feature

**Impact**: software change

**Release Notes**
Adds OpenSBI support to the software infrastructure (FireMarshal and Qemu). OpenSBI is now the default for all Marshal-managed workloads.

### CODE REVIEW

**Comment by NathanTP** [comment]
This shows libgloss as changed, but none of the commits seem to list it and I certainly never changed it. Not sure what that is all about (some quirk of git with merging dev?).

**Comment by a0u** [comment]
> This shows libgloss as changed, but none of the commits seem to list it and I certainly never changed it. Not sure what that is all about (some quirk of git with merging dev?).

Hmm, this situation illustrates why repeated back-merges can lose changes if the merge strategy isn't carefully chosen.
The PR branch actually points to ucb-bar/libgloss-htif@a88e50f2e1b0411e0a7d5e5c29d5b40117560912 (an old commit), whereas `dev` points to ucb-bar/libgloss-htif@04b249764b1bc0b784b9f7ff422084f4b53a07ef.

If there are no objections, I'll rebase and squash the QEMU and FireMarshal bumps into one cleaner commit.  From my experience, it wasn't necessary to bump riscv-isa-sim for OpenSBI, but that is probably harmless.

**Comment by NathanTP** [comment]
go for it, I really don't understand what happened considering this PR never touched it. Whatever.

**Comment by jerryz123** [comment]
IT should be sufficient to replace `branches=("master")` with
```
if [ "$CIRCLE_BRANCH" == "master" ] || [ "$CIRCLE_BRANCH" == "dev" ]
then
    branches=("master")
else
    branches=("master" "dev")
fi
```

**Pull request merged**
