### PR TITLE
Config finder `make` target

### PR DESCRIPTION
**Pull request by abejgonzalez**
Adds a new target to help users find *some* config fragments (also adds to the docs on how to use it).

Unfortunately, I wanted to do this through Scala reflection, however, that isn't possible since you can only look at the subclasses of `sealed` traits/classes. This is a simple solution that covers large majority of configs (assuming config. fragments are defined on a single line - "class NAME extends CONFIG\n"). This doesn't cover configs that don't inherit directly from `Config`... I don't have time to do that right now (or figure out a better way).

TODO:
- [ ] Right now just finds configs that are on the same line (`class NAME extends Config\n`). Extend this to match on multi-line (is there a scala-parser in Python that we can just read the scala file and see if there is an object that matches this).
- [x] Do successive greps through the code base to find child classes that extend from the main class (stop after a certain depth)

**Related PRs / Issues**:

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [x] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [ ] Build system change
- [x] Other

**Contributor Checklist**:
- [x] Did you set `main` as the base branch?
- [x] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you state the type-of-change/impact?
- [x] Did you delete any extraneous prints/debugging code?
- [x] Did you mark the PR with a `changelog:` label?
- [x] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [x] (If applicable) Did you add documentation for the feature?
- [x] (If applicable) Did you add a test demonstrating the PR?

- [x] (If applicable) Did you mark the PR as `Please Backport`?

### CODE REVIEW

**Comment by abejgonzalez** [comment]
Opening this up to see if people have any better ideas on how to do this (without some of the flaws)

**Comment by jerryz123** [comment]
Neat. Can you add this to build setup? I think this along with ctags can be the same step.

**Comment by abejgonzalez** [comment]
> Neat. Can you add this to build setup? I think this along with ctags can be the same step.

This dumps the configs at will, not into some file... Did you want this to be more visible?

**Comment by jerryz123** [comment]
Hmmm good point. Printing into a file probably isn't great for discoverability. 

This should be added to CI somewhere though.

**Review by sagark — APPROVED** [review]
LGTM

**Review by jerryz123 — APPROVED** [review]

**Review by jerryz123 — COMMENTED** [review]
Somehow my review comment didn't get posted. 

Can you fix the dump into /tmp? That's a bit concerning to me.

**Pull request merged**
