### PR TITLE
Bump barstools to use Scala 2.13

### LINKED ISSUE #1364: Barstools still uses Scala 2.12
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Release: main
Hash: 632a7a93482d5a57607d98d2512cf08f5105f620

### OS Setup

macOS 13.2.1

### Other Setup

Check out fresh Chipyard, run ./scripts/init-submodules-no-riscv-tools.sh

### Current Behavior

When building Chipyard after the Scala 2.13 update (https://github.com/ucb-bar/chipyard/pull/1303), barstools is still compiling with Scala 2.12. If you look in `tools/barstools/target`, there's a `scala-2.12` directory. I've got a project with some custom FIRRTL transforms which the `tapeout` project must depend on, and since `barstools` runs with Scala 2.12, my project must also run with Scala 2.12. I'd like to upgrade it to Scala 2.13 :)

### Expected Behavior

Barstools uses Scala 2.13 like the other Chipyard sub-projects.

I put together this PR for barstools which should resolve the problem: https://github.com/ucb-bar/barstools/pull/127

### Other Information

_No response_

### PR DESCRIPTION
**Pull request by tymcauley**
**Related PRs / Issues**:

Merges ucb-bar/barstools#127 and resolves #1364.

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [x] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [x] Build system change
- [ ] Other

**Contributor Checklist**:
- [ ] Did you set `main` as the base branch?
- [ ] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [ ] Did you state the type-of-change/impact?
- [ ] Did you delete any extraneous prints/debugging code?
- [ ] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

### CODE REVIEW

**Comment by tymcauley** [comment]
@jerryz123 any action I need to take to resolve this failure? https://github.com/ucb-bar/chipyard/actions/runs/4301027445/jobs/7511505150

Not sure if that's just a spurious problem, and the job needs to be restarted.

**Comment by tymcauley** [comment]
Huh, well now that same job has failed twice: https://github.com/ucb-bar/chipyard/actions/runs/4308888281/jobs/7515872594

Any clues as to why? Does the CI job need to by run by mergify or something?

**Comment by abejgonzalez** [comment]
Actually, #1367 added your changes in with another fix. Let's merge that PR in to get your changes.

**Comment by tymcauley** [comment]
Sounds good!

**Comment by abejgonzalez** [comment]
As for the CI issue, if PR'ing from a fork you don't have permissions to run CI. So you have to run mergify rebase/copy to create a new PR that is local to the repo to get permissions and run the CI (only devs on the repo can use mergify)

**Comment by tymcauley** [comment]
Makes sense, thanks!

**Pull request closed without merging**
