### PR TITLE
Ignore docs in CircleCI

### LINKED ISSUE #197: Skip CI checks on docs only updates
Seems like a waste of our limited CI resources to run them on PRs that only change docs like #196

### PR DESCRIPTION
**Pull request by abejgonzalez**
Added a webhook and a corresponding file to ignore the `docs` folder (according to this https://circleci.com/blog/circleci-hacks-automate-the-decision-to-skip-builds-using-a-git-hook/).

Note: The `add-githooks.sh` script needs to be run everytime a new repo is created.

Fixes #197

### CODE REVIEW

**Comment by colinschmidt** [comment]
I'm worried about the proliferation of scripts you `need to run` after creating a new repo. Does the note in this PR appear in the repo anywhere?

**Comment by abejgonzalez** [comment]
Sorry, what do you mean by note? I also would tend to agree on avoiding running extra scripts when cloning the repo. I'm willing to close this... especially since CI is faster.

**Comment by colinschmidt** [comment]
This:
`Note: The add-githooks.sh script needs to be run everytime a new repo is created.`

I do think CI is sufficiently fast to ignore this "free" win. There is no native circle-ci way to do this? I often see people put "[docs-only]" or something in their PR title. Can a solution like that work?

**Comment by abejgonzalez** [comment]
You can put `[skip ci]` in the commit message but you have to remember to do that.

This hook automates that by saying for every commit that touches the ignored dir, add a `[skip ci]` to it

**Comment by colinschmidt** [comment]
Ok. In that case I'm in favor of merging this.

**Comment by jwright6323** [comment]
What happens if a commit touches an ignored dir and real code?

**Comment by colinschmidt** [comment]
It won't be skipped.

**Comment by colinschmidt** [comment]
> What happens if a commit touches an ignored dir and real code?

See https://github.com/ucb-bar/chipyard/pull/218/files#diff-075b8fca921eaa87f41f58ce0278876aR26

**Comment by jwright6323** [comment]
got it, thanks

**Pull request merged**
