### PR TITLE
Bump esp-tools (March 2021)

### PR DESCRIPTION
**Pull request by zitaofang**
**Related issue**: N/A

**Type of change**: other enhancement

**Impact**: software change

**Release Notes**

Bump esp-tools to March 2021 version

### CODE REVIEW

**Comment by alonamid** [comment]
Should this also include a bump of upstream riscv-isa-sim and riscv-pk to keep them in sync?

**Comment by zitaofang** [comment]
This PR is ready. Check the PR listed above for submodule PR.

**Comment by alonamid** [comment]
Could this PR also bump riscv-tools to the equivalent commits, so we can make sure that esp-tools and riscv-tools are aligned?

**Comment by zitaofang** [comment]
Someone touched the instruction struct in the upstream Spike after my PR for multi-extension support was merged, breaking all of our custom extensions. Time is running out, so I am only modifying `esp-tools` (since people must use it if they want to use our extension anyway) to solve the problem for this release. I will submit another upstream PR to fix this bug, and we could merge that fix in the next bump.

**Comment by zitaofang** [comment]
Never mind, they fixed it in the latest version of spike.

**Review by alonamid — APPROVED** [review]
Suspecting there might bit a merge issue that may have overwritten some files (in particular, extension reset within `spike_main/spike.cc` ) , but will merge this since tests seem to pass with hwacha, and gemmini has added a workaround in the tests.

**Pull request merged**
