### PR TITLE
Removed FireSim tests and harnesses

### PR DESCRIPTION
**Pull request by nandor**
These tests were moved to FireSim itself. This PR removes them from Chipyard.

**Related PRs / Issues**:

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [x] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [ ] Build system change
- [x] Other

**Contributor Checklist**:
- [x] Did you set `main` as the base branch?
- [x] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you state the type-of-change/impact?
- x ] Did you delete any extraneous prints/debugging code?
- [x] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

### CODE REVIEW

**Comment by jerryz123** [comment]
Can you see my comment in the fsim PR where I raised this issue? I'd like to keep these tests if possible.

**Comment by jerryz123** [comment]
Ok I see how the tests are mirrored in firesim now, if this passes the CI I'll merge this.

**Comment by nandor** [comment]
Thanks!

**Review by jerryz123 — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
