### PR TITLE
Bump to gcc 13

### PR DESCRIPTION
**Pull request by vighneshiyer**
**Related PRs / Issues**:

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [x] Other enhancement

**Impact**:
- [ ] RTL change
- [x] Software change (RISC-V software)
- [ ] Build system change
- [ ] Other

**Contributor Checklist**:
- [x] Did you set `main` as the base branch?
- [x] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you state the type-of-change/impact?
- [x] Did you delete any extraneous prints/debugging code?
- [x] Did you mark the PR with a `changelog:` label?
- [x] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

Motivation for the bump is: 1) We should try to use the latest gcc to see if there are any regressions, 2) we should take advantage of any new compiler optimizations, and 3) verilator supposedly performs much better on large designs with `-Oz` which only exists in modern gcc. For now, I just want to see what breaks in CI.

### CODE REVIEW

**Review by abejgonzalez — APPROVED** [review]
LGTM (pending FS tests pass)

**Comment by jerryz123** [comment]
We should bump the RISCV toolchain to 13 as well.

**Comment by vighneshiyer** [comment]
@abejgonzalez The Firesim tests will pass once Firesim is bumped. Could you do that bump first, then I can rebase this branch on top of that bump?

**Comment by jerryz123** [comment]
Can you just do the bump in this PR? Just use the latest main of firesim

**Pull request merged**
