### PR TITLE
Bump to Chisel 3.5 RC 

### PR DESCRIPTION
**Pull request by davidbiancolin**
**Related issue**: Subsumes #998. See that PR for more discussion. I mostly used the existing submodule SHAs from the last PR. 

**Type of change**: other enhancement

**Impact**: other

**Release Notes**
Bump to Chisel 3.5 & FIRRTL 1.5 RC

### CODE REVIEW

**Comment by sequencer** [comment]
https://github.com/ucb-bar/rocket-dsp-utils/pull/6 may need as well, since those codes are too old to work.

**Comment by abejgonzalez** [comment]
> [ucb-bar/rocket-dsp-utils#6](https://github.com/ucb-bar/rocket-dsp-utils/pull/6) may need as well, since those codes are too old to work.

I'm not too familiar with `rocket-dsp-utils`... why is deleting those necessary? What uses those files?

**Comment by tymcauley** [comment]
I was just experimenting with this branch, and had one small comment: Due to the file-path changes in barstools, [the `SOURCE_DIRS` variable in `common.mk`](https://github.com/ucb-bar/chipyard/blob/4180463d52bc0a6b4c004530601ccdabebf0ab7d/common.mk#L74) should probably change from this:

```
SOURCE_DIRS = $(addprefix $(base_dir)/,generators sims/firesim/sim tools/barstools/iocell fpga/fpga-shells fpga/src)
```

to this:

```
SOURCE_DIRS = $(addprefix $(base_dir)/,generators sims/firesim/sim tools/barstools fpga/fpga-shells fpga/src)
```

(`tools/barstools/iocell` -> `tools/barstools`).

Also, in the current Chipyard `dev` branch, I've got a custom Chisel project added in (following [these directions](https://chipyard.readthedocs.io/en/latest/Customization/Custom-Chisel.html)), and I've got a few custom FIRRTL transforms defined in there. I'm able to run those transforms using syntax like this:

```
make CONFIG=... EXTRA_FIRRTL_OPTIONS="--custom-transforms custom.project.name.MyFirrtlTransform"
```

On this branch, I get this error at the `GenerateTopAndHarness` step:

```
[info] ------------------------------------------------------------------------------
[info] Error: Option --custom-transforms failed when given 'custom.project.name.MyFirrtlTransform'. Unable to locate custom transform custom.project.name.MyFirrtlTransform (did you misspell it?)
[info] Try --help for more information.
[info] ------------------------------------------------------------------------------
```

I thought this was due to the fact that in this branch (in `build.sbt`), the `tapeout` project no longer depends on the `chipyard` project (which in turn depends on our custom project). So I added a `dependsOn(...)` clause to the `tapeout` project, but that didn't work either. Any ideas on this? I can also file an issue to discuss this issue outside of this PR if you don't want this discussion to get too busy.

**Comment by abejgonzalez** [comment]
> I was just experimenting with this branch, and had one small comment: Due to the file-path changes in barstools, [the `SOURCE_DIRS` variable in `common.mk`](https://github.com/ucb-bar/chipyard/blob/4180463d52bc0a6b4c004530601ccdabebf0ab7d/common.mk#L74) should probably change from this:
> 
> ```
> SOURCE_DIRS = $(addprefix $(base_dir)/,generators sims/firesim/sim tools/barstools/iocell fpga/fpga-shells fpga/src)
> ```
> 
> to this:
> 
> ```
> SOURCE_DIRS = $(addprefix $(base_dir)/,generators sims/firesim/sim tools/barstools fpga/fpga-shells fpga/src)
> ```
> 
> (`tools/barstools/iocell` -> `tools/barstools`).

Good catch. I'll update this PR.

> Also, in the current Chipyard `dev` branch, I've got a custom Chisel project added in (following [these directions](https://chipyard.readthedocs.io/en/latest/Customization/Custom-Chisel.html)), and I've got a few custom FIRRTL transforms defined in there. I'm able to run those transforms using syntax like this:
> 
> ```
> make CONFIG=... EXTRA_FIRRTL_OPTIONS="--custom-transforms custom.project.name.MyFirrtlTransform"
> ```
> 
> On this branch, I get this error at the `GenerateTopAndHarness` step:
> 
> ```
> [info] ------------------------------------------------------------------------------
> [info] Error: Option --custom-transforms failed when given 'custom.project.name.MyFirrtlTransform'. Unable to locate custom transform custom.project.name.MyFirrtlTransform (did you misspell it?)
> [info] Try --help for more information.
> [info] ------------------------------------------------------------------------------
> ```
> 
> I thought this was due to the fact that in this branch (in `build.sbt`), the `tapeout` project no longer depends on the `chipyard` project (which in turn depends on our custom project). So I added a `dependsOn(...)` clause to the `tapeout` project, but that didn't work either. Any ideas on this? I can also file an issue to discuss this issue outside of this PR if you don't want this discussion to get too busy.

Hmmm. I don't know about this issue. However, this seems separate from this PR? Maybe open an issue on the FIRRTL repo and see what the recommended way to run custom transforms is?

**Comment by tymcauley** [comment]
> > I thought this was due to the fact that in this branch (in `build.sbt`), the `tapeout` project no longer depends on the `chipyard` project (which in turn depends on our custom project). So I added a `dependsOn(...)` clause to the `tapeout` project, but that didn't work either. Any ideas on this? I can also file an issue to discuss this issue outside of this PR if you don't want this discussion to get too busy.
> 
> Hmmm. I don't know about this issue. However, this seems separate from this PR? Maybe open an issue on the FIRRTL repo and see what the recommended way to run custom transforms is?

I figured that this issue might have more to do with how Chipyard sets up sbt project dependencies, but I could be wrong. In any case, I filed #1103 so we can move the discussion there. There are some minimal examples for reproducing the issue.

**Pull request merged**
