### PR TITLE
Update Initial-Repo-Setup.rst to force `conda-lock` version

### LINKED ISSUE #1488: `conda install -n base conda-lock` no longer works with existing Lockfiles due to new `conda-lock` release
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/chipyard)
- [X] Yes, I searched [prior issues](https://github.com/ucb-bar/chipyard/issues)
- [X] Yes, I searched the [documentation](https://chipyard.readthedocs.io/)

### Chipyard Version and Hash

Release: 1.5.0
Hash: a6a6a6

### OS Setup

Darwin rohanmbp.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64

conda-lock version 2.0.0

### Other Setup

Followed documentation for setting up Chipyard repository.

### Current Behavior

conda-lock is unable to read Lockfiles during `./build-setup.sh`

### Expected Behavior

conda-lock should be able to parse Lockfiles (works when constrained to version 1.4.0 using `conda install -n base conda-lock=1.4.0`)

### Other Information

_No response_

### PR DESCRIPTION
**Pull request by rohanku**
**Related PRs / Issues**:

Fixes #1488

**Type of change**:
- [x] Bug fix
- [ ] New feature
- [ ] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [ ] Build system change
- [x] Other

**Contributor Checklist**:
- [x] Did you set `main` as the base branch?
- [ ] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [ ] Did you state the type-of-change/impact?
- [ ] Did you delete any extraneous prints/debugging code?
- [ ] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

### CODE REVIEW

**Review by jerryz123 — APPROVED** [review]

**Review by abejgonzalez — COMMENTED** [review]
Does this work with any `conda-lock` version greater than `0.*`. We use the following for our environment which is a bit more flexible. https://github.com/ucb-bar/chipyard/blob/0b07958e6c4f7c0f6177f0d4a998c6e49333b4cb/conda-reqs/chipyard.yaml#L96

**Comment by rohanku** [comment]
I could do `conda-lock=1`, since  `conda-lock>=1` no longer works (version 2.0.0 is the one that is causing issues).

**Comment by abejgonzalez** [comment]
> I could do `conda-lock=1`, since `conda-lock>=1` no longer works (version 2.0.0 is the one that is causing issues).

Lets do that then (if you can also update the lockfiles by changing [chipyard/conda-reqs/chipyard.yaml](https://github.com/ucb-bar/chipyard/blob/0b07958e6c4f7c0f6177f0d4a998c6e49333b4cb/conda-reqs/chipyard.yaml#L96) and running: https://github.com/ucb-bar/chipyard/blob/main/scripts/generate-conda-lockfiles.sh

**Comment by abejgonzalez** [comment]
Update: I'll do this quickly in another PR (since this PR is from a fork).

**Comment by rohanku** [comment]
Sorry I didn't get around to it, but that would be great. I don't actually have conda on my computer anymore since I decided to install the dependencies I needed manually.

**Pull request closed without merging**
