### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by abejgonzalez**
**Related issue**: 

**Type of change**: bug fix + other enhancement

**Impact**: other

**Release Notes**
Fixes issue where README shown would default to the `.github/README.md` instead of the top-level `README.md`. Additionally adds a new section at the top of the `README.md` for quick links. My reasoning for adding this is that it makes it extremely easy to find the link to the mailing list (called forum here) for people who don't care to read down the `README.md`. This aligns with #1029 where I pointed to the mailing list more.

### CODE REVIEW

**Comment by jerryz123** [comment]
What is the README bug? Having multiple READMEs should be supported.

**Comment by abejgonzalez** [comment]
> What is the README bug? Having multiple READMEs should be supported.

If there is a README in the `.github` area, it will show that one by default instead of the one in the top-level of the repo.

**Comment by jerryz123** [comment]
Its useful to have README.md in the subdirectories, as it shows up when you browse there in Github, I think this may be a one-off rendering bug, rather than a repo bug.

Here's a screenshot of what I mean. If you rename it this will not longer show up.

image

**Comment by abejgonzalez** [comment]
> Its useful to have README.md in the subdirectories, as it shows up when you browse there in Github, I think this may be a one-off rendering bug, rather than a repo bug.
> 
> Here's a screenshot of what I mean. If you rename it this will not longer show up.
> 
> image

I agree, but I think this is an issue with the priority of the `.github` vs the root directory `README.md` file... I would look at the two PR commits to see the difference.

**Review by jerryz123 — APPROVED** [review]

**Pull request merged**
