### PR TITLE
Bump libgloss

### PR DESCRIPTION
**Pull request by a0u**
**Related issue**: 

**Type of change**: other enhancement

**Impact**: software change

**Release Notes**
Bump libgloss_htif for trap handler support.

### CODE REVIEW

**Comment by tymcauley** [comment]
Should we re-bump libgloss given this new commit?

https://github.com/ucb-bar/libgloss-htif/commit/a88e50f2e1b0411e0a7d5e5c29d5b40117560912

 Or is there more work planned there?

**Comment by tymcauley** [comment]
@a0u do you want me to open up a new PR with the latest commit from libgloss-htif?

**Comment by a0u** [comment]
@tymcauley: I've opened one in #516.  I was waiting to see if there was more user feedback about the fix before bumping, but I'll take this is as a sign that things are working.

**Comment by tymcauley** [comment]
Great, thanks @a0u! Ya, before adding in this fix, any attempt to return from a trap resulted in a corrupted stack pointer, but this commit fixes that for me.

**Pull request merged**
