### PR TITLE
fix: remove e2fsprogs

### PR DESCRIPTION
**Pull request by tianrui-wei**
**Related PRs / Issues**:

**Type of change**:
- [x] Bug fix
- [ ] New feature
- [ ] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [x] Build system change
- [ ] Other

**Contributor Checklist**:
- [x] Did you set `main` as the base branch?
- [ ] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you state the type-of-change/impact?
- [ ] Did you delete any extraneous prints/debugging code?
- [ ] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

### CODE REVIEW

**Comment by abejgonzalez** [comment]
Can you update the conda lock file

**Comment by tianrui-wei** [comment]
@abejgonzalez Just updated the lockfiles

**Review by abejgonzalez — CHANGES_REQUESTED** [review]
Can you revert all things being unpinned and just remove e2fsprogs and regenerate the lockfile. We can't unpin things just yet.

**Review by jerryz123 — CHANGES_REQUESTED** [review]
we definitely aren't ready to bump to 1.0.3 riscv-tools yet, I think.

**Comment by abejgonzalez** [comment]
Let's hold off on this PR for now. FireSim is in the process of unpinning all its deps as much as possible which should help this RV tools bump: https://github.com/firesim/firesim/pull/1451

**Comment by tianrui-wei** [comment]
Closed in favor of https://github.com/ucb-bar/chipyard/pull/1394

**Pull request closed without merging**
