### PR TITLE
Bump Barstools

### PR DESCRIPTION
**Pull request by abejgonzalez**
This is bumping `barstools` to have a couple of macro-compiler bug fixes and cleanup.

### CODE REVIEW

**Comment by abejgonzalez** [comment]
@davidbiancolin It looks like CI is failing on not finding a `GroundTestBridge` module in `firechip`. I previously bumped FireSim in #326 to recent `dev`. Did I miss something?

**Comment by davidbiancolin** [comment]
Well this is mystifying, how did CI pass before?

**Comment by abejgonzalez** [comment]
@davidbiancolin found the error, unfortunately firesim was reverted in this commit on accident: https://github.com/ucb-bar/chipyard/commit/443be014958fa8066dba1f64f923abd90c56726b.

I rebumped FireSim to a new `dev` commit.

**Comment by davidbiancolin** [comment]
Alright so the error in the midasexample is a known issue and is resolved [here](https://github.com/firesim/firesim/pull/419/commits/80d558363cf48e28e007276f043992e346a7391e). 

We have a couple options. Either you can bump to the same commit you used before, or i can pull the test fix out into a separate PR in firesim, we can merge that, and you can bump again.

**Comment by abejgonzalez** [comment]
Fixed the single test case in FireSim and re-bumped according to @davidbiancolin's request

**Pull request merged**
