### PR TITLE
Various improvements and fixes

### PR DESCRIPTION
**Pull request by jerryz123**
- Support for TightlyCoupledMemory (TCM) in the Spike model, allowing for fast Linux boot with RTL simulation of the uncore with the SpikeUltraFastConfig
- Add new "chosen" node to DTS, to request earlycon be with the sifive uart.
- Add hello-world bare-metal program
- Fix BOOM marchid
- Fix icenet/rocc issues with default marshal kernel
- Re-add password login

TODO:

- [x] Add note on docs explaining spike-TCM
- [x] Add RTL sim of linux boot with peripheral devices  + drivers to CI

**Related PRs / Issues**:

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [ ] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [ ] Build system change
- [ ] Other

**Contributor Checklist**:
- [ ] Did you set `main` as the base branch?
- [ ] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [ ] Did you state the type-of-change/impact?
- [ ] Did you delete any extraneous prints/debugging code?
- [ ] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

### CODE REVIEW

**Review by abejgonzalez — COMMENTED** [review]
We should add a SpikeUltraFastConfig Linux boot test with RoCC instructions in CI just to ensure that things work properly.

**Comment by jerryz123** [comment]
Unfortunately I wasn't able to speed-up SpikeUltraFast fast enough to get it to chew through user code fast enough for CI.

**Comment by abejgonzalez** [comment]
> Unfortunately I wasn't able to speed-up SpikeUltraFast fast enough to get it to chew through user code fast enough for CI.

Can we just add a simple test of something that just does a single user space RoCC instruction and finishes? Like build Gemmini Spike model and just do a Gemmini TLB flush.

**Comment by jerryz123** [comment]
Even after 30 minutes, the SpikeUltraFast has not made its way through init. More work needs to be done to improve its performance before we can have full boot-poweroff CI on it, unfortunately.

**Comment by jerryz123** [comment]
We need to merge this while rc-blocks is failing because the fix was squash-merged into rc-blocks. #1411 will fix this.

**Comment by jerryz123** [comment]
@abejgonzalez I say we go for merge on this, #1411 is basically ready, and that will fix some of the commit-on-master checks

**Review by abejgonzalez — APPROVED** [review]
LGTM.

**Pull request merged**
