### PR TITLE
Set ENABLE_SBT_THIN_CLIENT to 1 as default for CY conda-env

### PR DESCRIPTION
**Pull request by joey0320**
**Related PRs / Issues**:

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [x] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [ ] Build system change
- [x] Other

**Contributor Checklist**:
- [x] Did you set `main` as the base branch?
- [x] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you state the type-of-change/impact?
- [x] Did you delete any extraneous prints/debugging code?
- [x] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

### CODE REVIEW

**Comment by jerryz123** [comment]
Perhaps it's neater to make thin client the default in the makefile. And have a new flag DISABLE_THIN_CLIENT use the old behavior. 

Then we don't have to manage another environment variable.

**Comment by abejgonzalez** [comment]
I personally don't like having this be the default since there is no way to auto-terminate the daemon if CY switches branches, is deleted, etc. This flag will lead a lot of folks having dangling build servers lying around that they would have to cancel themselves. I like it disabled for super users to find out about and consciously deal with (including managing when to shutdown the server or realize it's dangling).

**Comment by joey0320** [comment]
> I personally don't like having this be the default since there is no way to auto-terminate the daemon if CY switches branches, is deleted, etc. This flag will lead a lot of folks having dangling build servers lying around that they would have to cancel themselves. I like it disabled for super users to find out about and consciously deal with (including managing when to shutdown the server or realize it's dangling).
> 
> For example, I had to add the following code in my `bashrc` to auto-shutdown any potential server.
> 
> https://github.com/abejgonzalez/dotfiles/blob/771757d8643f417c6e45e80f376ab1af56085a01/.bash_common#L27-L36
> 
> Maybe if we use bloop this problem would be solved (I'm considering re-looking into this since using a bloop build server would integrate well with VSCode + NVim metals).



> I personally don't like having this be the default since there is no way to auto-terminate the daemon if CY switches branches, is deleted, etc. This flag will lead a lot of folks having dangling build servers lying around that they would have to cancel themselves. I like it disabled for super users to find out about and consciously deal with (including managing when to shutdown the server or realize it's dangling).
> 
> For example, I had to add the following code in my `bashrc` to auto-shutdown any potential server.
> 
> https://github.com/abejgonzalez/dotfiles/blob/771757d8643f417c6e45e80f376ab1af56085a01/.bash_common#L27-L36
> 
> Maybe if we use bloop this problem would be solved (I'm considering re-looking into this since using a bloop build server would integrate well with VSCode + NVim metals).

I see. Do you think it would be too messy if we just added the above code to each user's bashrc when we run `build-setup.sh`?

**Comment by jerryz123** [comment]
We should not append stuff to users bashrc. 

I agree with Abe then, we ought to leave this as an optional feature. Power users can add it to their bashrc if they want.

**Pull request closed without merging**
