### PR TITLE
Ensure all GPIO signals are tied off

### PR DESCRIPTION
**Pull request by tymcauley**
**Related PRs / Issues**:

Resolves ucb-bar/chipyard#1731.

**Type of change**:
- [x] Bug fix
- [ ] New feature
- [ ] Other enhancement

**Impact**:
- [x] RTL change
- [ ] Software change (RISC-V software)
- [ ] Build system change
- [ ] Other

**Contributor Checklist**:
- [x] Did you set `main` as the base branch?
- [ ] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you state the type-of-change/impact?
- [ ] Did you delete any extraneous prints/debugging code?
- [ ] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

### CODE REVIEW

**Review by T-K-233 — APPROVED** [review]
Look good. 
Thanks!

**Review by jerryz123 — CHANGES_REQUESTED** [review]
LGTM as well, but before we do, the PR to rocket-chip-blocks must be merged.

**Comment by tymcauley** [comment]
Okay, finally got that rocket-chip-blocks PR merged, thanks @jerryz123. Not sure if the rocket-chip-blocks bump is pulling in more changes than desired now, or if this is okay.

**Comment by jerryz123** [comment]
This is good, thanks!

**Review by jerryz123 — APPROVED** [review]

**Comment by jerryz123** [comment]
Ok odd... this broke SPI flash.. I don't think this is related to your changes... but warrants some investigation

**Comment by tymcauley** [comment]
> Ok odd... this broke SPI flash.. I don't think this is related to your changes... but warrants some investigation

I guess this is the first time that this PR is getting pulled into Chipyard, which does touch the SPI controller: https://github.com/chipsalliance/rocket-chip-blocks/pull/25

**Comment by jerryz123** [comment]
Thanks for chasing down the commit. I've reverted it on rocket-chip-blocks

**Comment by tymcauley** [comment]
> Thanks for chasing down the commit. I've reverted it on rocket-chip-blocks

np! I've merged that change into here, hopefully CI is all fixed now.

**Pull request merged**
