### PR TITLE
Documentation: Change "don't use Windows" to "if using Windows, use WSL"

### PR DESCRIPTION
**Pull request by JL102**
**Related PRs / Issues**:

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [x] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [ ] Build system change
- [x] Other

**Contributor Checklist**:
- [x] Did you set `main` as the base branch?
- [ ] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you state the type-of-change/impact?
- [x] Did you delete any extraneous prints/debugging code?
- [ ] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

I don't believe this PR needs to be included on the changelog, as it's an extremely minor documentation tweak.

### CODE REVIEW

**Comment by jerryz123** [comment]
I'm hesitant to encourage users to try installing this with WSL, as they would be on their own troubleshooting any issues related to WSL. 

OTOH, with Conda, WSL support may be more stable now, enough for basic use-cases. 

@abejgonzalez thoughts?

**Comment by abejgonzalez** [comment]
Does Chipyard work under WSL? I'm not sure Conda views it as linux-64? In any case, I think it's fine to say experimental support for WSL, and most devs use normal Linux assuming that WSL is stable enough now.

What works and doesn't on WSL?

**Comment by JL102** [comment]
I've used Chipyard on WSL many times with no issues (at least, no issues that aren't **also** issues on native Linux systems, like #1441). I've only used Verilator, though, so I haven't tried all of Chipyard's tools. But WSL2 is extremely stable as it's basically just a Linux system.

**Comment by JL102** [comment]
> I'm not sure Conda views it as linux-64?

@abejgonzalez How do you get Conda to print what OS/environment it thinks it's in? I can test it but don't know what command(s) to run to check. I'm fairly sure it'll think the system is linux-64 but it's worth checking.

**Comment by abejgonzalez** [comment]
> > I'm not sure Conda views it as linux-64?
> 
> @abejgonzalez How do you get Conda to print what OS/environment it thinks it's in? I can test it but don't know what command(s) to run to check. I'm fairly sure it'll think the system is linux-64 but it's worth checking.

Sorry I missed this. I don't know about printing out the env. information that Conda see's. I also presume that it is just counted as Linux.

**Comment by harrisonliew** [comment]
Chiming in here as I use Chipyard in WSL2 (Ubuntu) with no issues.

`conda info` returns this in the report: `platform : linux-64`. WSL uses a full [Linux 5.15.xx kernel](https://github.com/microsoft/WSL2-Linux-Kernel).

**Comment by T-K-233** [comment]
Also confirms that it works for me with Windows 10 running Ubuntu 22.04 under WSL2. 

Only issue found is on USB device discovery and connection (only needed for FPGA prototyping etc., so shouldn't matter that much)

**Review by jerryz123 — APPROVED** [review]

**Comment by harrisonliew** [comment]
@T-K-233 regarding FPGA prototyping, you could just use the Windows version of Vivado Lab? But yes, I agree that USB devices in WSL2 are a PITA (but I did get it working at one point using [these instructions](https://learn.microsoft.com/en-us/windows/wsl/connect-usb) and other resources around the internet).

**Comment by T-K-233** [comment]
> @T-K-233 regarding FPGA prototyping, you could just use the Windows version of Vivado Lab? But yes, I agree that USB devices in WSL2 are a PITA (but I did get it working at one point using [these instructions](https://learn.microsoft.com/en-us/windows/wsl/connect-usb) and other resources around the internet).

Yes, I'm running Windows Vivado + Windows version of the RISC-V toolchains to debug FPGA DUT. 

For those who face similar issue, [here](https://notes.tk233.xyz/chipyard-soc-fpga/setting-up-risc-v-toolchain/setting-up-risc-v-toolchain-windows)'s how I set up the Windows-side environment.

**Comment by abejgonzalez** [comment]
Ah. SG then. If more than 1 person is using it semi-successfully then this should be more than fine. Sorry for the delay on this PR.

**Pull request merged**
