### PR TITLE
docs: Update FireSim docs

### PR DESCRIPTION
**Pull request by geekLucian**
Some docs about FireSim is a bit out-dated:
1. After `source sourceme-manager.sh`, we need `firesim managerinit --platform f1` to do some extra prep work before continuing.
2. `sims/firesim/deploy/deploy/config_build_recipes.ini` doesn't exist, it was refactored into `sims/firesim/deploy/config_build_recipes.yaml`
3. Fix some broken links to FireSim docs

Also, I added a reference to FireSim docs on [how to build custom hardware design with FireSim](https://docs.fires.im/en/stable/Getting-Started-Guides/AWS-EC2-F1-Getting-Started/Initial-Setup/Setting-up-your-Manager-Instance.html), should be beneficial to include that.

**Related PRs / Issues**:

**Type of change**:
- [x] Bug fix
- [ ] New feature
- [ ] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [ ] Build system change
- [x] Other

**Contributor Checklist**:
- [x] Did you set `main` as the base branch?
- [ ] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you state the type-of-change/impact?
- [x] Did you delete any extraneous prints/debugging code?
- [ ] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

### CODE REVIEW

**Comment by jerryz123** [comment]
Re: 2).. that file should appear after managerinit has been executed. The user should not reference or modify sample_backup_configs. We could add a clarifying note on this though.

**Comment by geekLucian** [comment]
> Re: 2).. that file should appear after managerinit has been executed. The user should not reference or modify sample_backup_configs. We could add a clarifying note on this though.

Yeah, I added `manager-init` in the previous setup commands already, so that file should appear by that stage

**Comment by geekLucian** [comment]
> Re: 2).. that file should appear after managerinit has been executed. The user should not reference or modify sample_backup_configs. We could add a clarifying note on this though.

Oh that's a typo in the description, that's not what was there in the modification

**Review by jerryz123 — COMMENTED** [review]
@abejgonzalez

**Review by abejgonzalez — APPROVED** [review]

**Pull request merged**
