### PR TITLE
Add WithUARTInitBaud/fix firesim uart configs

### PR DESCRIPTION
**Pull request by jerryz123**
**Related PRs / Issues**:

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [ ] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [ ] Build system change
- [ ] Other

**Contributor Checklist**:
- [ ] Did you set `main` as the base branch?
- [ ] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [ ] Did you state the type-of-change/impact?
- [ ] Did you delete any extraneous prints/debugging code?
- [ ] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

### CODE REVIEW

**Review by abejgonzalez — APPROVED** [review]

**Comment by abejgonzalez** [comment]
> Duplication of #1511 ?

This fixes an issue with #1511 (FireSim designs would have 2 UARTs with incorrect baudrates).

**Comment by jerryz123** [comment]
Fixed in this PR

**Review by abejgonzalez — APPROVED** [review]
Re-approved. Waiting on a bitstream build to check the baudrate changes. Thanks Jerry

**Comment by jerryz123** [comment]
I'll fix this together with reverting the reversion in another PR.

**Pull request closed without merging**
