### PR TITLE
Bump to Verilator v5.022

### PR DESCRIPTION
**Pull request by vighneshiyer**
**Related PRs / Issues**:

**Type of change**:
- [x] Bug fix
- [ ] New feature
- [ ] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [x] Build system change
- [ ] Other

**Contributor Checklist**:
- [x] Did you set `main` as the base branch?
- [x] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you state the type-of-change/impact?
- [x] Did you delete any extraneous prints/debugging code?
- [x] Did you mark the PR with a `changelog:` label?
- [x] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

Verilator v5.020 has a bug when building a debug simulator (https://github.com/verilator/verilator/issues/4860). Bumping the Verilator version resolves this issue.

### CODE REVIEW

**Comment by vighneshiyer** [comment]
Running `make debug` in `verilator/sims` with Verilator v5.020 causes the issue linked above. You can't compile a debug simulator

**Comment by jerryz123** [comment]
Ah nice, Vikram was running into this

**Comment by vighneshiyer** [comment]
@abejgonzalez Could you check on the CI? I'm able to run `./build-setup.sh` on the Millennium machines just fine, but the CI fails during the `conda-lock` step. Maybe the base conda environment needs to be re-installed?

**Comment by jerryz123** [comment]
The `setup-repo` step in some other currently running jobs worked fine.
I wonder if this is related to the ` Error: EBUSY: resource busy or locked` failures.

**Comment by jerryz123** [comment]
I think you just have to manually delete '/scratch/buildbot/actions-runner-7/_work/chipyard/chipyard/software/firemarshal/disk-mount` off the build machines

**Review by abejgonzalez — APPROVED** [review]
LGTM. Pending CI passing.

**Comment by aignacio** [comment]
can you make another release with this fix? latest v1.11 is still on 5.20 which is broken...

**Comment by seldridge** [comment]
Note that 5.022 has a major bug in `force` behavior if you are using that [1]. This is fixed in 5.024.

[1]: https://github.com/verilator/verilator/issues/5062

**Pull request merged**
