### PR TITLE
add pyright

### PR DESCRIPTION
**Pull request by joey0320**
QOL

**Related PRs / Issues**:

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [x] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [ ] Build system change
- [x] Other

**Contributor Checklist**:
- [x] Did you set `main` as the base branch?
- [x] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you state the type-of-change/impact?
- [x] Did you delete any extraneous prints/debugging code?
- [x] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

### CODE REVIEW

**Comment by abejgonzalez** [comment]
FireSim uses `mypy`. Whats the difference between this and `mypy`?

**Comment by abejgonzalez** [comment]
I'm not opposed to this. Could you also change the `mypy` in FireSim to `pyright` (and all associated checks)?

**Comment by joey0320** [comment]
It looks like there isn't a official version of the pyright-boto checker. We can make a feedstock out of some guys repo but that will be somewhat janky (the repo isn't maintained).
Anyways, w

**Comment by abejgonzalez** [comment]
Closing since stale. This can be re-opened if this is worked on again.

**Pull request closed without merging**
