### PR TITLE
Bump ESP Spike

### PR DESCRIPTION
**Pull request by alonamid**
**Related issue**: https://groups.google.com/forum/#!topic/chipyard/4pBzTO76gLw

**Type of change**: bug fix

**Impact**: software change

**Release Notes**
Bump esp-isa-sim 

This bump was likely missed during the Chipyard 1.2 release, which creates a mismatch between the Gemmini Spike model and the Gemmini RTL implementation

### CODE REVIEW

**Comment by hngenc** [comment]
Lgtm

**Comment by colinschmidt** [comment]
Should we have spike run some tests in CI to avoid this breakage in the future?

**Comment by alonamid** [comment]
Worth discussing adding a Spike test to the esp-tools CI test

**Comment by colinschmidt** [comment]
Spike tests run very fast so if we already build these tools (which I think we do) then there is pretty little downside IMO.

**Pull request merged**
