### PR TITLE
firesim: Add a config with no mem port

### PR DESCRIPTION
**Pull request by davidbiancolin**
**Related PRs / Issues**:

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [ ] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [ ] Build system change
- [ ] Other

**Contributor Checklist**:
- [ ] Did you set `main` as the base branch?
- [ ] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [ ] Did you state the type-of-change/impact?
- [ ] Did you delete any extraneous prints/debugging code?
- [ ] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

### CODE REVIEW

**Review by jerryz123 — APPROVED** [review]

**Comment by michael-etzkorn** [comment]
Not sure if the ordering comes into play since I haven't looked at `WithFireSimConfigTweaks` but I think some users would like a `RocketNoMemPortConfig` with no FireSim so this could be two separate configs. 

Something like:

```scala
 class NoMemPortRocketConfig extends Config(
  new freechips.rocketchip.subsystem.WithNoMemPort ++
  new testchipip.WithBackingScratchpad ++
  new chipyard.RocketConfig)
```

```scala
class FireSimNoMemPortConfig extends Config(
  new WithDefaultFireSimBridges ++
  new WithFireSimConfigTweaks ++
  new chipyard.NoMemPortRocketConfig)
```

**Comment by davidbiancolin** [comment]
@michael-etzkorn That would be great. If you wanted to PR that I'd highly appreciate it as i'm quite short on time atm.

**Comment by michael-etzkorn** [comment]
> @michael-etzkorn That would be great. If you wanted to PR that I'd highly appreciate it as i'm quite short on time atm.
Probably best to merge this now and I'll make a note to make a PR to break it up. That PR will probably happen whenever I circle back to my chipyard-related project and am bumping chipyard versions.

**Comment by michael-etzkorn** [comment]
> @michael-etzkorn That would be great. If you wanted to PR that I'd highly appreciate it as i'm quite short on time atm.
Probably best to merge this now and I'll make a note to make a PR to break it up. That PR will probably happen whenever I circle back to my chipyard-related project and am bumping chipyard versions.

**Pull request merged**
