### PR TITLE
Remove skip-validate option

### PR DESCRIPTION
**Pull request by joey0320**
The default installation option should not ask "y/n".
I think most people would want to run `build-setup.sh` and walk away 🥲 

**Related PRs / Issues**:

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [ ] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [ ] Build system change
- [ ] Other

**Contributor Checklist**:
- [ ] Did you set `main` as the base branch?
- [ ] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [ ] Did you state the type-of-change/impact?
- [ ] Did you delete any extraneous prints/debugging code?
- [ ] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

### CODE REVIEW

**Comment by jerryz123** [comment]
I personally agree with this change

**Comment by jerryz123** [comment]
It's probably a good idea to leave the flags as no-ops so people's existing flows and documentation won't all immediately break.

**Comment by jerryz123** [comment]
> > It's probably a good idea to leave the flags as no-ops so people's existing flows and documentation won't all immediately break.
> 
> 
> 
> Hmmm.... but then we need to cleanup the "no-op" flags later...

Yeah, at some point. But IMO this is an instance where we should prioritize minimizing user pain.

**Comment by joey0320** [comment]
There are times when radical changes just have to take place.......

**Comment by jerryz123** [comment]
> There are times when radical changes just have to take place.......

Removing the flag and all relevant documentation is fine. 

Leaving behind the parsing as a no-op is a minimal QoL feature that has no impact otherwise.

**Comment by joey0320** [comment]
Hmm.. I think it is even more confusing to users if there is a "flag that does nothing".

**Comment by joey0320** [comment]
😢

**Comment by jerryz123** [comment]
Remove it from the documentation and help text. Users should not be able to discover it and be confused. 

It would only affect existing users following old docs, or with their own scripts.

**Comment by SeahK** [comment]
Oh, this change seems good. I sometimes forget to do Y and waste an hour.

**Review by SeahK — APPROVED** [review]

**Comment by T-K-233** [comment]
Nice change. I will update the tutorials when we do a version release with this change.

**Review by T-K-233 — APPROVED** [review]

**Comment by jerryz123** [comment]
I'd like to wait for @abejgonzalez and @sagark before merge.

**Review by jerryz123 — CHANGES_REQUESTED** [review]
Wait for @abejgonzalez and @sagark

**Comment by joey0320** [comment]
😠

**Comment by joey0320** [comment]
Release has to happen...

**Comment by jerryz123** [comment]
I know, but as others have asked for this feature in the past, it would be rude to unilaterally remove it without their feedback.

**Comment by abejgonzalez** [comment]
This is going to get rejected by @sagark most likely. This flag being there exists strictly for new users who accidentally don't check out a release to have some sort of prompt telling them "Hey this isn't a release, this may not work".

**Comment by jerryz123** [comment]
If @sagark concedes then we can merge this, after my backwards-compatibility concerns are addressed. I think we certainly have some consensus that this is the right move. 

FWIW, this isn't the Wild West of rocket-chip and RTL changes between releases anymore... at this point, most changes are strictly QoL improvements or new-features. The latest commit on main is much more likely to be usable than the latest release, and we will continue to only provide support for the latest main. 

Thus, I don't see the benefit of pushing users into using tagged releases.

**Comment by sagark** [comment]
> FWIW, this isn't the Wild West of rocket-chip and RTL changes between releases anymore... at this point, most changes are strictly QoL improvements or new-features. The latest commit on main is much more likely to be usable than the latest release, and we will continue to only provide support for the latest main.
> 
> Thus, I don't see the benefit of pushing users into using tagged releases.

I'll approve, let's give it a try.

Since this is so early in the setup process, I also think it's fine to just delete the flag completely (no deprecation warning), as long as we've scrubbed references to it throughout the docs/code. It'll just error immediately for anyone using the flag and then they can fix it.

**Review by sagark — APPROVED** [review]

**Review by jerryz123 — APPROVED** [review]
Thanks for bringing this up @joey0320

**Pull request merged**
