### PR TITLE
Don't shallow clone submodules (revert #1064)

### PR DESCRIPTION
**Pull request by jerryz123**
**Related PRs / Issues**:

Reverts #1064. Shallow clones cause myriad problems,

**Type of change**:
- [x] Bug fix
- [ ] New feature
- [ ] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [x] Build system change
- [ ] Other

**Contributor Checklist**:
- [x] Did you set `main` as the base branch?
- [x] Did you delete any extraneous prints/debugging code?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as "Please Backport"?

**Release Notes**

### CODE REVIEW

**Comment by jerryz123** [comment]
It appears firesim points to some backport

**Comment by abejgonzalez** [comment]
@jerryz123 is this ready to merge?

**Comment by jerryz123** [comment]
Not yet. I need to check why this still seems to have some git errors in CI

**Comment by jerryz123** [comment]
I don't really know why this is failing. Was not able to reproduce locally.

**Comment by DorianXGH** [comment]
Did you manage to get the same commit hashes for the submodules ? Idk, it seems like the CI pipeline fails to find the right commits.

**Comment by abejgonzalez** [comment]
Have you fully reverted both https://github.com/ucb-bar/chipyard/pull/1125 and https://github.com/ucb-bar/chipyard/pull/1064. Seems like you should just move the submodule init back outside the `search_submodule` loop to fully revert. IDK if that solves the problem but worth a shot.

**Comment by jerryz123** [comment]
Those changes only affect the check-commit script? The error in CI shouldn't be related to that, (I'm looking at the prepare-chipyard jobs).

**Comment by abejgonzalez** [comment]
Hmm. On further look, I'm also quite stumped. I've gone ahead and added some debug prints but this is still very weird.

**Review by abejgonzalez — CHANGES_REQUESTED** [review]
Pending fix, remove my checkmark

**Review by abejgonzalez — APPROVED** [review]
This should be fixed now. I think this was some weird issue with the FireSim tests / CI that was fixed with the extra `cd`.

**Comment by abejgonzalez** [comment]
The tests are failing because FireSim needs to get the libdwarf fix.

**Comment by jerryz123** [comment]
I don't see how the firesim script would have affected the init-submodules for the chipyard-only jobs, but it looks like they work now?

On the other hand, firesim tests seem to fail for libdwarf now.

**Comment by jerryz123** [comment]
Do you want to just merge this and fix libdwarf in another PR?

**Comment by abejgonzalez** [comment]
Yea it was really weird, it looked like the `firesim-` jobs in the workflow would run first, mess up the repository, fail, then go on to the `prepare-` steps. The `cd` helps in general but is probably not the main fix (was probably a combo of this fix + me clearing the old repos from the CI machine itself).

I think this PR is ready to merge. I think @sagark is planning on minor releasing soon which would bump FireSim in CY for the libdwarf fix.

**Comment by jerryz123** [comment]
Ok. I'll merge it now then. Thanks for looking at it.

**Pull request merged**
