### PR TITLE
Add support for FSDB

### PR DESCRIPTION
**Pull request by jerryz123**
**Related issue**: #1070 

**Type of change**: new feature

**Impact**:  software change

**Release Notes**

- Add support for FSDB file format in VCS flow

### CODE REVIEW

**Comment by jerryz123** [comment]
@SihaoLiu is there anything else needed for this?

**Comment by SihaoLiu** [comment]
I think most of mofification are similar, just some options are missing, I added here
https://github.com/ucb-bar/chipyard/pull/1073

**Comment by SihaoLiu** [comment]
Sorry, I don't think it is correct, please ignore the last PR

**Comment by jerryz123** [comment]
@SihaoLiu I just pushed another commit with the kdb, lca flags added.

**Comment by SihaoLiu** [comment]
@jerryz123 Are you sure we don't need `-P ${VERDI_HOME}/share/PLI/VCS/LINUX64/novas.tab ${VERDI_HOME}/share/PLI/VCS/LINUX64/pli.a` ? At least on my end I need this to make fsdb dump work.

Maybe something like:
```
ifdef USE_FSDB
WAVEFORM_FLAG=+fsdbfile=$(sim_out_name).fsdb
VCS_OPTS += -kdb -P ${VERDI_HOME}/share/PLI/VCS/LINUX64/novas.tab ${VERDI_HOME}/share/PLI/VCS/LINUX64/pli.a
else
WAVEFORM_FLAG=+vcdplusfile=$(sim_out_name).vpd
endif
```

**Comment by jerryz123** [comment]
My simv linked correctly, and I was able to open the FSDB without those flags. What error does adding those flags fix?

**Comment by SihaoLiu** [comment]
Did you add something related to verdi to your LD_LIBRARY_PATH? And what verdi version you are using?

**Comment by jerryz123** [comment]
It was sufficient for me to set `$VERDI_HOME`, I am using Verdi P-2019.06 with VCS P-2019.06

**Comment by SihaoLiu** [comment]
@jerryz123 Ok let me test on my end later today

**Comment by lduncan-nb** [comment]
I can confirm that this works fine without the extra flags with version Q-2020.03-SP2-2 of both VCS and Verdi

**Comment by SihaoLiu** [comment]
I can also confirm that this works without `-P ${VERDI_HOME}/share/PLI/VCS/LINUX64/novas.tab ${VERDI_HOME}/share/PLI/VCS/LINUX64/pli.a` for running `make USE_FSDB=1 BINARY=$RISCV/riscv64-unknown-elf/share/riscv-tests/isa/rv64ui-p-simple run-binary-debug`

I think it works

**Comment by lduncan-nb** [comment]
After a bit more testing, this is breaking the default VPD build for me with this error:
```
Error-[UST] Undefined System Task Call
/share/snorlax/scratch/luke/fsdb/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig/TestDriver.v, 146
  Undefined System Task call to '$fsdbDumpoff'.
   


Error-[UST] Undefined System Task Call
/share/snorlax/scratch/luke/fsdb/sims/vcs/generated-src/chipyard.TestHarness.RocketConfig/TestDriver.v, 154
  Undefined System Task call to '$fsdbDumpoff'.
```

Can anyone confirm? I believe this is caused by having `+definte+FSDB` in `PREPROC_DEFINES` which causes TestDriver to always call the FSDB dump functions instead of the VPD ones.

**Comment by lduncan-nb** [comment]
I had also been working on enabling FSDB dumps here: lduncan-nb@2efd51e7a2a7d2f2a10441843dfba33a41477b50

It conditionally adds the additional options only when FSDBs are enabled so it seems to properly generate both VPDs and FSDBs. If you'd like me to submit a separate PR for that one, let me know.

**Comment by lduncan-nb** [comment]
> I met this problem before, you need to link `-P ${VERDI_HOME}/share/PLI/VCS/LINUX64/novas.tab ${VERDI_HOME}/share/PLI/VCS/LINUX64/pli.a` for a dirty fix.

Wouldn't it still be an issue that TestDriver will use the `fsdbDump*` tasks instead of `vcdplus*`?
https://github.com/chipsalliance/rocket-chip/blob/a7b016e46e22e4fdc013357051e30511f80df082/src/main/resources/vsrc/TestDriver.v#L80-L89
```
`ifdef FSDB
`define VCDPLUSON $fsdbDumpon;
`define VCDPLUSCLOSE $fsdbDumpoff;
`elsif VCS
`define VCDPLUSON $vcdpluson(0); $vcdplusmemon(0);
`define VCDPLUSCLOSE $vcdplusclose; $dumpoff;
`else
`define VCDPLUSON $dumpon;
`define VCDPLUSCLOSE $dumpoff;
`endif
```

VPD dumps work just fine for me if I remove `+define+FSDB` from `PREPROC_DEFINES`

**Comment by jerryz123** [comment]
Yeah the define should be guarded by the flag. I'll update the PR tomorrow.

**Comment by jerryz123** [comment]
Updated.

**Comment by lduncan-nb** [comment]
It looks like some of the new flags are triggering additional warnings in VCS Q-2020.03-SP2-2, but otherwise everything seems to be working fine with the latest commit.

```
Warning-[DEBUG_DEP] Option will be deprecated
  The option '-debug_pp' will be deprecated in a future release.  Please use 
  '-debug_acc+pp+dmptf -debug_region+cell+encrypt' instead.


Warning-[DBGACC_DBG] Multiple debug options being used
  The debug switches '-debug_access' and '-debug_pp' are being used together. 
  For better performance, consider using only '-debug_access'.


Warning-[LCA_FEATURES_ENABLED] Usage warning
  LCA features enabled by '-lca' argument on the command line.  For more 
  information regarding list of LCA features please refer to Chapter "LCA 
  features" in the VCS Release Notes


Warning-[DEBUG_DEP] Option will be deprecated
  The option 'debug=4' will be deprecated in a future release.  Please use 
  '-debug_acc+pp+f+fn+dmptf -debug_region+cell+encrypt' instead.
```

**Review by abejgonzalez — CHANGES_REQUESTED** [review]
Can you document the `USE_FSDB` in the `make help` command. Otherwise LGTM

**Review by abejgonzalez — APPROVED** [review]

**Pull request merged**
