### PR TITLE
Heterogeneous doc patches

### PR DESCRIPTION
**Pull request by tymcauley**
**Related issue**: #786 

**Type of change**: documentation

**Impact**: documentation

**Release Notes**
Fix documentation for Heterogeneous SoCs, add documentation on hart ID ordering.

### CODE REVIEW

**Comment by jerryz123** [comment]
The ordering is sequential from bottom up (or right to left), following the behavior of other config fragments.
In other words
```
WithNLargeBooms(2) ++
WithNBigCores(1)
```
Generates 
hart0: Rocket
hart1/2: LargeBoom

**Comment by tymcauley** [comment]
Great, thanks @jerryz123 ! In that case, looking at this config:

```scala
class LargeBoomAndHwachaRocketConfig extends Config(
  new chipyard.config.WithMultiRoCC ++                                  // support heterogeneous rocc
  new chipyard.config.WithMultiRoCCHwacha(1) ++                         // put hwacha on hart-1 (rocket)
  new hwacha.DefaultHwachaConfig ++                                     // set default hwacha config keys
  new boom.common.WithNLargeBooms(1) ++                                 // add 1 boom core
  new freechips.rocketchip.subsystem.WithNBigCores(1) ++                // add 1 rocket core
  new chipyard.config.AbstractConfig)
```

the rocket core should be hart 0, and the boom core hart 1. That means we should change `WithMultiRoCCHwacha(1)` to `WithMultiRoCCHwacha(0)` if we want the Hwacha connected to the Rocket core, correct?

**Comment by jerryz123** [comment]
Oh yeah, that comment is wrong. That should be `WithMultiRoCCHwacha(0)` to put it on Rocket. Thanks for the catch.

**Comment by tymcauley** [comment]
Alright, I fixed that issue, and I also added some text at the bottom of that page explaining hart ID ordering in a bit more detail.

**Comment by tymcauley** [comment]
Alright, I'm happy with this PR, let me know if you'd like me to change anything.

**Review by jerryz123 — APPROVED** [review]
Thanks for the fixes.

**Review by alonamid — APPROVED** [review]
LGTM. Thank you for these corrections!

**Pull request merged**
