### PR TITLE
Bump firrtl, avoid double-emitting annotations to reduce heap usage

### PR DESCRIPTION
**Pull request by albert-magyar**
This bumps FIRRTL and changes some logic in how annotations are dumped to JSON in barstools. This avoids the out-of-memory issues that were happening with bumped FIRRTL submodules.

Barstools PR: ucb-bar/barstools#64

### CODE REVIEW

**Comment by albert-magyar** [comment]
Chipyard PR: ucb-bar/chipyard#183

**Comment by albert-magyar** [comment]
It's not chisel :)

**Comment by colinschmidt** [comment]
That hasn't stopped problems from cropping up before :)
I guess we did have to change the emission stuff in barstools.

**Comment by abejgonzalez** [comment]
Confirms this builds the `MegaBoomConfig`.

**Pull request merged**
