### PR TITLE
New Scala-based Config Finder

### PR DESCRIPTION
**Pull request by abejgonzalez**
`make find-config-fragments` now searches for all configs using the classpath instead of `greps`. A slight downside to this approach is that you don't get the filename of the config... but this should still be better and more robust than the `grep` methodology.

**Related PRs / Issues**:

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [x] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [ ] Build system change
- [x] Other

**Contributor Checklist**:
- [x] Did you set `main` as the base branch?
- [x] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you state the type-of-change/impact?
- [x] Did you delete any extraneous prints/debugging code?
- [x] Did you mark the PR with a `changelog:` label?
- [x] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [x] (If applicable) Did you add documentation for the feature?
- [x] (If applicable) Did you add a test demonstrating the PR?

- [x] (If applicable) Did you mark the PR as `Please Backport`?

### CODE REVIEW

**Comment by abejgonzalez** [comment]
@mergifyio rebase

**Comment by abejgonzalez** [comment]
@jerryz123 ping

**Comment by jerryz123** [comment]
Cool. Can you paste here what the generated stuff looks like?

**Review by jerryz123 — APPROVED** [review]

**Comment by abejgonzalez** [comment]
image

**Pull request merged**
