### PR TITLE
Update SiFive submodules to CHIPS fork

### PR DESCRIPTION
**Pull request by michael-etzkorn**
SiFive versions of repos will no longer be actively maintained so they've been transferred over to Chipsalliance. 

**Related PRs / Issues**:

https://github.com/ucb-bar/chipyard/issues/1171

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [x] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [x] Build system change
- [ ] Other

**Contributor Checklist**:
- [x] Did you set `main` as the base branch?
- [ ] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you state the type-of-change/impact?
- [x] Did you delete any extraneous prints/debugging code?
- [ ] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

### CODE REVIEW

**Comment by michael-etzkorn** [comment]
I can't add a changelog label, but the label would be omit.

**Comment by michael-etzkorn** [comment]
I'll fix the CI run commit check for this over the weekend.

**Comment by michael-etzkorn** [comment]
@jerryz123 This should now pass the check-commit CI job. fpga-shells' main branch is now named main and I've updated the script to reflect that.

**Review by jerryz123 — APPROVED** [review]

**Review by jerryz123 — APPROVED** [review]

**Review by abejgonzalez — APPROVED** [review]
LGTM

**Pull request merged**
