### PR TITLE
Add UART and UARTAdapter to all configs

### PR DESCRIPTION
**Pull request by abejgonzalez**
This PR adds a UART to all systems and adds a UARTAdapter in the TestHarness to talk to the UART.

Things to do:
- [x] Add UART to all configurations

### CODE REVIEW

**Comment by colinschmidt** [comment]
Does this affect simulation speed?

**Comment by abejgonzalez** [comment]
Yes. But I don't think by much if you are not running code that outputs to the UART.

**Comment by abejgonzalez** [comment]
@colinschmidt Do you want me to check something specifically?

**Comment by abejgonzalez** [comment]
Note: This works with Linux boot in simulation with baudrate 115200 on the adapter.

**Comment by abejgonzalez** [comment]
> LGTM. Is there some place in the docs where we should now mention what this config class does?

I just added a quick section on the adapter in the documentation. I can add more later if necessary.

**Pull request merged**
