### PR TITLE
Scratchpad Documentation Fix

### PR DESCRIPTION
**Pull request by abejgonzalez**
**Related issue**: #567 

**Type of change**: bug fix

**Impact**: other

**Release Notes**
Fixes the docs.

### CODE REVIEW

**Comment by jerryz123** [comment]
I'm actually in favor of not documenting or including the DTIM scratchpad option. It doesn't seem to be something we would ever use.

**Comment by alonamid** [comment]
Is there a reason not to document it?

**Comment by jerryz123** [comment]
It's not our job to document all of rocketchip, especially the features which we don't regularly use.

**Comment by abejgonzalez** [comment]
It sounds like external users like both options described (2 external people looked at the documentation and asked questions / gave feedback on it). So I think its beneficial to keep it.

**Comment by alonamid** [comment]
To the actual content of the PR - there seems to be a mismatch between the text and the code example. You remove the memory port in the L1 code example, but in the text you say that you should do that for the mbus scratchpad case.

**Comment by abejgonzalez** [comment]
No I do that for both cases?

**Comment by alonamid** [comment]
you're right, github diff got me again...

**Pull request merged**
