### PR TITLE
Control Core Example

### PR DESCRIPTION
**Pull request by abejgonzalez**
Example MultiCore configuration with a small "control" core attached on the side (i.e. a PMU). This was requested by @jwright6323 and @alonamid.

### CODE REVIEW

**Comment by abejgonzalez** [comment]
Note: This doesn't choose what `hartId` the simple core has... I can change this if need be.

**Comment by jwright6323** [comment]
I think we want it the way you wrote it - the control core should be the last hart ID.

**Comment by abejgonzalez** [comment]
So that gets overridden by the `new boom.common.WithRenumberHarts ++` line. If we want it as the last `hartId` I can move it to after that line.

**Comment by colinschmidt** [comment]
Looks good.

**Pull request merged**
