### PR TITLE
Update initial setup scripts

### PR DESCRIPTION
**Pull request by abejgonzalez**
**Related issue**: #867 

**Type of change**: other enhancement

**Impact**:other

**Release Notes**
Test if these changes are backwards compatible.

@KarlJoad

### CODE REVIEW

**Review by alonamid — APPROVED** [review]
LGTM, but it might be worth it to kick CI to make sure nothing was accidently cached.

**Comment by timsnyder-siv** [comment]
I think bintray is also mentioned in https://github.com/ucb-bar/chipyard/blob/KarlJoad-update-initial-setup-scripts/scripts/centos-req.sh and https://github.com/ucb-bar/chipyard/blob/KarlJoad-update-initial-setup-scripts/scripts/ubuntu-req.sh that get included into the docs.  Those scripts should also be updated so that the docs are consistent.

**Comment by timsnyder-siv** [comment]
Please ignore my earlier comment.  I'm trying to wake up this morning...

**Comment by abejgonzalez** [comment]
Opened single PR to test this #874

**Pull request closed without merging**
