### PR TITLE
Let user specify existing PREFIX/RISCV for toolchain installs

### PR DESCRIPTION
**Pull request by jerryz123**
I like to manage my `$RISCV` independently.

### CODE REVIEW

**Comment by alonamid** [comment]
In this case, if you've installed riscv-tools, and now decide you want to install esp-tools, you need to actively clean your RISC-V environment variable (otherwise it will silently now install esp-tools). Is there a way to indicate this to the unsuspecting user?

**Comment by jerryz123** [comment]
> In this case, if you've installed riscv-tools, and now decide you want to install esp-tools, you need to actively clean your RISC-V environment variable (otherwise it will silently now install esp-tools). Is there a way to indicate this to the unsuspecting user?

Why would I need to actively clean my RISCV directory? The script should just overwrite existing files in there when it builds esp-tools.

**Comment by a0u** [comment]
What @alonamid probably meant was, if one intends to build an alternative toolchain but has already sourced `env.sh`, the user must remember to unset `RISCV` to avoid overwriting the original installation.

I am fine with supporting arbitrary installation paths, but an explicit command line option (`-d <path>`) would be preferable instead.  Regardless of the approach, the user-specified input should also be converted into an absolute path, if not already one, to avoid a subsequent configure error.

**Comment by sagark** [comment]
+1 to @a0u

**Comment by jerryz123** [comment]
I added a `--prefix` option. I also incremented the CI cached tools index, so the build-tools tests reran.

**Pull request merged**
